/**
 * The Vexto mark, as the numbers the inline SVG draws — generated by
 * `frontend/tools/brand/generate.mjs` from `frontend/tools/brand/geometry.mjs`.
 * Do not edit by hand.
 *
 * `VxLogo` renders from these, and `branding/*.svg` is written from the same source in the same
 * run, so the mark in the sidebar and the mark in an email signature cannot drift apart.
 */

/** The square the mark is drawn in. */
export const VEXTO_MARK_BOX = 32;

/** The two converging route strokes. */
export const VEXTO_MARK_ROUTE = 'M7.8 6.8 L14.8 25.2 L19.8 12.2';

/** Weight of the route strokes. */
export const VEXTO_MARK_ROUTE_WIDTH = 5.2;

/** The detached waypoint node. */
export const VEXTO_MARK_WAYPOINT = {"cx":24,"cy":6.8,"r":2.7} as const;

/** Translation that centres the mark's ink in the box. */
export const VEXTO_MARK_OFFSET = {"dx":0.05,"dy":0.05} as const;

/** Ink bounds inside the box — what clear space and minimum sizes are measured against. */
export const VEXTO_MARK_INK = {
  width: 21.5,
  height: 23.7,
} as const;

/**
 * An ink-tight viewBox, so an inline `<svg>` element's own box *is* the mark rather than the
 * padded square. That is what lets a template lay the mark out by the height it appears to be.
 */
export const VEXTO_MARK_INK_VIEWBOX = '5.2 4.1 21.5 23.7';

/** Ink width ÷ ink height. */
export const VEXTO_MARK_ASPECT = 0.907;

/**
 * The lockup's two proportions, shared with `branding/vexto-logo-horizontal.svg` so the inline
 * lockup and the asset are the same logo: the wordmark's cap height as a share of the mark's ink
 * height, and the gap between them as a share of the same.
 */
export const VEXTO_WORDMARK_CAP_RATIO = 0.59;
export const VEXTO_LOCKUP_GAP_RATIO = 0.228;

/**
 * Inter's cap height as a share of its font size. A template sizes the wordmark by cap height and
 * divides by this to get a `font-size`.
 */
export const INTER_CAP_RATIO = 0.73;

/**
 * The favicon's optical variant: a shorter arm and a slightly larger node, so the gap survives
 * being drawn 16px wide. See `geometry.mjs`.
 */
export const VEXTO_FAVICON_ROUTE = 'M7.8 6.8 L14.8 25.2 L19.4 13.2';
export const VEXTO_FAVICON_ROUTE_WIDTH = 5;
export const VEXTO_FAVICON_WAYPOINT = {"cx":24.3,"cy":6.5,"r":2.95} as const;
export const VEXTO_FAVICON_OFFSET = {"dx":-0.275,"dy":0.375} as const;
